name: powershell-scripts-validation
# Validate the changes to PowerShell scripts

# Workflow triggered by a change under the 'Scripts' folder - but can also be triggered manually
on:
  push:
    branches: [ main ]
    paths:
      - 'Scripts/**'
      - '!.devcontainer/**'
      - '!.github/**'
      - '!.vscode/**'
      - '!Configuration/**'
      - '!Data/**'
      - '!Website/**'
      - '!.gitignore'
      - '!CODE_OF_CONDUCT.md'
      - '!LICENSE'
      - '!README.md'
  workflow_dispatch:

# Concurrency configuration for the current workflow - Keep only the latest workflow queued for the considered group and the considered issue
concurrency:
  group: powershell-scripts-validation
  cancel-in-progress: true

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:
      # Action used to checkout the main branch in the current repository
      #   Community action: https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v4.1.1

      # Run tests on all *.Tests.ps1 files
      - name: Run Pester tests
        run: Invoke-Pester
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_ACCESS_PUBLIC_GITHUB_REPOSITORIES }}

  PSScriptAnalyzer:
    runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:
      # Action used to checkout the main branch in the current repository
      #   Community action: https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v4.1.1

      # Run PSScriptAnalyzer on all *.ps1 files
      #  Community action: https://github.com/microsoft/psscriptanalyzer-action
      - name: Run PSScriptAnalyzer
        uses: microsoft/psscriptanalyzer-action@v1.1
        with:
          path: .\
          recurse: true
          output: results.sarif

      # Upload the results of the PSScriptAnalyzerResults execution
      #   Action: https://github.com/actions/upload-artifact
      - name: Upload PSScriptAnalyzer Results
        uses: actions/upload-artifact@v3
        with:
          name: PSScriptAnalyzerResults
          path: results.sarif
      
      # Upload the SARIF file generated in the previous step
      #   Community action: https://github.com/github/codeql-action
      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
